name: Publish to Cargo

on:
  push:

jobs:
  publish_lib:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install curl
        run: sudo apt install curl

      - name: Setup Rust
        run: echo "1" | (curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh)
